"""Utilitários para gerar um relatório PDF simples com metadados, pedido e resposta.

Dependência: reportlab
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import textwrap


def _draw_wrapped_text(c, x, y, text, max_width, leading=12):
    lines = []
    for paragraph in str(text).splitlines():
        wrapped = textwrap.wrap(paragraph, width=100)
        if not wrapped:
            lines.append('')
        else:
            lines.extend(wrapped)

    for line in lines:
        c.drawString(x, y, line)
        y -= leading
    return y


def generate_api_report_pdf(path, metadata, request_info, response_info, notes=None):
    """Gera um PDF com estrutura:
    - Cabeçalho e metadados
    - Request (headers e resumo do body)
    - Response (status, tipo detectado, summary, artifact se houver)
    - Notes/observações
    """
    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    margin = 20 * mm
    x = margin
    y = height - margin

    # Título
    c.setFont('Helvetica-Bold', 16)
    c.setFillColor(colors.darkblue)
    c.drawString(x, y, 'API Call Report')
    y -= 12

    c.setFont('Helvetica', 9)
    y -= 6

    # Metadados
    c.setFillColor(colors.black)
    y -= 10
    meta_lines = [f"Generated at: {metadata.get('generated_at')}", f"Endpoint: {metadata.get('api_endpoint')}", f"Method: {metadata.get('method')}]"]
    for line in meta_lines:
        c.drawString(x, y, line)
        y -= 12

    y -= 6
    c.setFont('Helvetica-Bold', 12)
    c.drawString(x, y, 'Request')
    y -= 14
    c.setFont('Helvetica', 9)
    # Headers
    headers = request_info.get('headers') or {}
    if headers:
        c.drawString(x, y, 'Headers:')
        y -= 12
        for k, v in headers.items():
            y = _draw_wrapped_text(c, x + 6, y, f"{k}: {v}", max_width=width - 2*margin)
            y -= 4

    body_summary = request_info.get('body_summary')
    if body_summary:
        c.drawString(x, y, 'Body summary:')
        y -= 12
        y = _draw_wrapped_text(c, x + 6, y, body_summary, max_width=width - 2*margin)
        y -= 4

    y -= 8
    c.setFont('Helvetica-Bold', 12)
    c.drawString(x, y, 'Response')
    y -= 14
    c.setFont('Helvetica', 9)
    resp_lines = [f"Status code: {response_info.get('status_code')}", f"Detected type: {response_info.get('detected_type')}", f"Summary: {response_info.get('summary')}"]
    for line in resp_lines:
        y = _draw_wrapped_text(c, x, y, line, max_width=width - 2*margin)
        y -= 6

    artifact = response_info.get('artifact')
    if artifact:
        c.drawString(x, y, f"Artifact: {artifact}")
        y -= 12

    if notes:
        y -= 6
        c.setFont('Helvetica-Bold', 11)
        c.drawString(x, y, 'Notes')
        y -= 12
        c.setFont('Helvetica', 9)
        y = _draw_wrapped_text(c, x, y, notes, max_width=width - 2*margin)

    # Footer
    c.setFont('Helvetica', 8)
    c.setFillColor(colors.grey)
    c.drawString(margin, 12, 'Generated by BizDocs_Integrator')

    c.showPage()
    c.save()
